services:
  postgres-db1:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=carmen1
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password1
    ports:
      - "5432:5432"
    volumes:
      - db1-data:/var/lib/postgresql/data
      - ./carmen1.sql:/carmen1.sql

  postgres-db2:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=coffee-shop
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=password2
    ports:
      - "5433:5432"
    volumes:
      - db2-data:/var/lib/postgresql/data
      - ./coffee_shop_db.sql:/coffee_shop_db.sql

volumes:
  db1-data:
  db2-data:
